server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: db-migration
  profiles:
    active: ${ENVIRONMENT}

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: ${DATABASE_DRIVER}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        ddl-auto: validate
        default_schema: ${DATABASE_SCHEMA}
    show-sql: true

  flyway:
    table: tb_migration
    locations: classpath:db/migration

app:
  log:
    path: ${APP_LOG_PATH}
    level: ${APP_LOG_LEVEL}

---

spring:
  config:
    activate:
      on-profile: dev

#---
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: uat
#
#server:
#  ssl:
#    certificate: ${SSL_CERTIFICATE_FILE}
#    certificate-private-key: ${SSL_CERTIFICATE_KEY}
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#server:
#  ssl:
#    certificate: ${SSL_CERTIFICATE_FILE}
#    certificate-private-key: ${SSL_CERTIFICATE_KEY}